name: Build and Push Docker Image for hello-spring-k8s

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt Java (vì cần build ứng dụng Spring Boot)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build và push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./hello-spring-k8s
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-spring-k8s:latest